insert into doctor (id,name, specialist) values (0,'Paweł Kosiński','proktolog');
insert into doctor (id,name, specialist) values (1,'Jan Nowak','kardiolog');
insert into doctor (id,name, specialist) values (2,'Roma Kleszcz','psycholog');
insert into doctor (id,name, specialist) values (3,'Janusz Kowalski','dentysta');
insert into doctor (id,name, specialist) values (4,'Rafał Wawrzyniak','psychiatra');
insert into patient (id,name, adress) values (0,'Roman Wozniak','Kamienna 23, 64-005 Pleszew');
insert into patient (id,name, adress) values (1,'Karolina Piękna','Cudowna 23, 64-006 Szwecja');
insert into patient (id,name, adress) values (2,'Konrad Adamski','Brudna 23, 64-005 Zchlap');
insert into patient (id,name, adress) values (3,'Mariusz Kozłowski','Stok 23, 65-005 Plastowo');
insert into patient (id,name, adress) values (4,'Mistrz Karol','Mistrzowska 23, 64-005 Kaczory');
commit;
