insert into doctor (id,name, specialist) values (,'Paweł Kosiński','proktolog');
insert into doctor (name, specialist) values ('Jan Nowak','kardiolog');
insert into doctor (name, specialist) values ('Roma Kleszcz','psycholog');
insert into doctor (name, specialist) values ('Janusz Kowalski','dentysta');
insert into doctor (name, specialist) values ('Rafał Wawrzyniak','psychiatra');
insert into patient (name, adress) values ('Roman Wozniak','Kamienna 23, 64-005 Pleszew');
insert into patient (name, adress) values ('Karolina Piękna','Cudowna 23, 64-006 Szwecja');
insert into patient (name, adress) values ('Konrad Adamski','Brudna 23, 64-005 Zchlap');
insert into patient (name, adress) values ('Mariusz Kozłowski','Stok 23, 65-005 Plastowo');
insert into patient (name, adress) values ('Mistrz Karol','Mistrzowska 23, 64-005 Kaczory');
commit;
